### PR TITLE
[WIP] Error messages

### PR DESCRIPTION
**Pull request by dhalperi**
See #283

### CODE REVIEW

**Comment by dhalperi** [comment]
@7andrew7 might we chat about this briefly tomorrow? Been trying to the bugs myself to ensure that I can keep the parser up, and have some design questions. See the TODO in commit 2fd9008.

Some questions about rules. E.g., for [Unbox](https://github.com/uwescience/raco/blob/master/raco/myrial/parser.py#L818),

```python
    @staticmethod
    def p_sexpr_id_dot_id(p):
        'sexpr : unreserved_id DOT unreserved_id'
        p[0] = sexpr.Unbox(p[1], p[3])

    @staticmethod
    def p_sexpr_id_dot_pos(p):
        'sexpr : unreserved_id DOT DOLLAR INTEGER_LITERAL'
        p[0] = sexpr.Unbox(p[1], p[4])
```

why are these two variants explicitly spelled out instead of using the [`column_ref` expression](https://github.com/uwescience/raco/blob/master/raco/myrial/parser.py#L768).

Second, more germane to this bug, why isn't there an `alias` expression that we used in place of the `unreserved_id` in the two definitions here, as well as where the `('ALIAS', ..)` tuple is created: https://github.com/uwescience/raco/blob/master/raco/myrial/parser.py#L768 . Then we wouldn't need to handle the two different types of `rex` in the code in that fix.

(I will fix the bugs myself, but would appreciate your advice!)

**Comment by dhalperi** [comment]
I updated the `column_ref` redundancy in c643da3, and that worked fine.

In a different branch, I had my idea for using `ALIAS`, but I clearly was misguided. I think an Alias means something different than I was thinking. (see c208f18 in another branch, which is buggy.)

**Comment by 7andrew7** [comment]
I think this is a parser bug -- i.e., the code should generate a parse error instead of some sort of relation not found error.  I'm cooking up an alternate fix...

**Comment by 7andrew7** [comment]
As you probably deduced, the logic here was very convoluted.  I tried to simplify things in #383.

Conceptually, every table in a from clause has a name (a string) and a corresponding Operator.  The previous Unboxing implementation was hideous in that it allowed the name to sometimes be a tuple containing an AST.  Let me know if #383 clarifies the situation.

**Pull request merged**
